<a href="https://colab.research.google.com/github/mipaillafil/mly1101-machine-learning-portafolio/blob/main/1.1.2_Verificacion_Entorno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Script de diagnóstico del entorno MLY1101
import sys
import numpy as np
import pandas as pd
import matplotlib
print("=== DIAGNÓSTICO DEL ENTORNO DE DESARROLLO ===")
print(f"Versión de Python instalada: {sys.version}")
print(f"Versión de NumPy: {np.__version__}")
print(f"Versión de Pandas: {pd.__version__}")
print(f"Versión de Matplotlib: {matplotlib.__version__}")
print("============================================")
print("¡Entorno verificado con éxito para análisis exploratorio!")

=== DIAGNÓSTICO DEL ENTORNO DE DESARROLLO ===
Versión de Python instalada: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Versión de NumPy: 2.0.2
Versión de Pandas: 2.2.2
Versión de Matplotlib: 3.10.0
============================================
¡Entorno verificado con éxito para análisis exploratorio!

###Arreglos Multidimensionales (NDArrays)

In [2]:
import numpy as np
# Creación de un arreglo e incremento vectorial
pesos = np.array([75.5, 82.1, 90.4, 68.9])
pesos_ajustados = pesos * 1.05
print(pesos_ajustados)
# Output rápido y directo sin loops

[79.275 86.205 94.92  72.345]

###Estructuras de Datos de Pandas

In [13]:
import pandas as pd
# Creación de una Serie con índice
ventas = pd.Series([450, 600, 320],
index=['Ene', 'Feb', 'Mar'])
print(ventas['Feb'])
# Acceso directo por etiqueta
# Estructura típica de una matriz de datos
data = {
'edad': [23, 45, 31],
'compras': [120.5, 450.0, 85.2]
}
df = pd.DataFrame(data)
df

600

   edad  compras
0    23    120.5
1    45    450.0
2    31     85.2

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   edad     3 non-null      int64
 1   compras  3 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 180.0 bytes
None

###.loc y .iloc

In [7]:
df.loc[0,'edad']

np.int64(23)

In [11]:
df.iloc[0,0]

np.int64(23)

### Guía 1.2.2

###**Paso 1: Preparación del Entorno e Importación de Librerías**

In [14]:
import numpy as np
import pandas as pd
import os

###**Paso 2: Descarga de Datos de Kaggle y Carga en Memoria**

In [16]:
# Carga inicial controlando delimitadores y codificación estándar
df_clientes = pd.read_csv('ecommerce_customer_data.csv', sep=',',
encoding='utf-8')
# Inspección de las dimensiones de la matriz de datos
print(f"Dimensiones del dataset cargado: {df_clientes.shape}")

Dimensiones del dataset cargado: (10000, 14)

###**Paso 3: Perfilamiento Estructural del Dataset**

In [17]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [18]:
df_clientes.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

###**Paso 4: Computación Vectorial con NumPy**

In [20]:
#Extraer columna EstimatedSalary como un arreglo Numpy
montos_brutos = df_clientes['EstimatedSalary'].to_numpy()

#Calcular gasto neto de operación con tasa impositiva fija del 19% + un costo operativo logistico.
gasto_neto = montos_brutos * 1.19 + 2.5

#Guardamos el resultado en una nueva columna del DataFrame
df_clientes['GastoNetoOperación'] = gasto_neto

###**Paso 5: Segmentación y Aislamiento Avanzado**

In [22]:
#Extraer segmento clientes + su gasto neto
clientes_gastos = df_clientes.iloc[49:100, [1, 14]]

print(clientes_gastos)

    CustomerId  GastoNetoOperación
49    15771873         230980.4528
50    15616550         235692.9004
51    15768193         102847.7383
52    15683553         139206.5461
53    15702298         195211.2186
54    15569590          47620.0644
55    15760861         134960.9831
56    15630053         103660.5083
57    15647091          54282.8625
58    15623944           1957.8009
59    15804771          55665.0832
60    15651280         100568.8883
61    15773469         150531.3358
62    15702014         212772.2747
63    15751208         118286.5484
64    15592461         110482.8973
65    15789484          33034.9484
66    15696061         131415.9969
67    15641582         234043.7032
68    15638424         135254.1515
69    15755648          21664.0700
70    15703793          33767.3934
71    15620344          40407.6053
72    15812518          52604.7245
73    15779052          69530.4039
74    15770811         173221.7560
75    15780961          26644.2200
76    15614049         165604.8516
77    15662085         176373.1616
78    15575185         231147.6597
79    15803136         116981.4159
80    15706021         203984.7554
81    15663706         162387.7461
82    15641732          30965.8121
83    15701164         189492.4951
84    15738751           2272.6154
85    15805254         136466.6425
86    15762418         153088.0865
87    15625759         180727.0265
88    15622897         110971.6898
89    15767954         186584.2184
90    15757535         207306.7118
91    15731511         175090.1274
92    15809248         130443.8383
93    15640635         205028.3259
94    15676966         102321.6393
95    15699461         144323.0582
96    15738721          76870.8475
97    15693683         234761.0947
98    15604348         118580.0976
99    15633059           7778.1742

###**Paso 6: Análisis de Eficiencia Física**

**Exportar a Excel**

In [ ]:
#Guardamos el dataset actualizado
df_clientes.to_csv(
    'ecommerce_clientes_resultado.csv',
    index=False,
    encoding='utf-8'
)

print("Archivo CSV creado correctamente.")

**Comprobamos los archivos creados**

In [23]:
# Revisamos los archivos que existen en la carpeta actual
print("Archivos disponibles:")

for archivo in os.listdir():
    print(archivo)

Archivos disponibles:
.config
ecommerce_customer_data.csv
sample_data